import { AuditService } from './auditService';
import { AuditLogEntry, AuditLogQuery, AuditReport, AuditStatistics } from './types';
import { randomUUID } from 'crypto';
import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

/**
 * HIPAA-Compliant Audit Report Generator
 */
export class AuditReportGenerator {
  /**
   * Generate comprehensive audit report
   */
  static async generateReport(
    startDate: Date,
    endDate: Date,
    generatedBy: string,
    options: {
      includeLogs?: boolean;
      reportType?: 'summary' | 'detailed' | 'compliance';
      filters?: Partial<AuditLogQuery>;
    } = {}
  ): Promise<AuditReport> {
    const { includeLogs = true, reportType = 'detailed', filters = {} } = options;

    // Query logs
    const query: AuditLogQuery = {
      startDate,
      endDate,
      ...filters,
      limit: includeLogs ? 10000 : 0, // Limit for performance
    };

    const logs = includeLogs ? await AuditService.query(query) : [];
    const statistics = await this.calculateStatistics(logs, startDate, endDate);

    const report: AuditReport = {
      reportId: randomUUID(),
      reportType,
      generatedAt: new Date(),
      generatedBy,
      startDate,
      endDate,
      summary: {
        totalLogs: statistics.totalLogs,
        totalUsers: Object.keys(statistics.logsByUser).length,
        totalPatients: Object.keys(statistics.logsByPatient).length,
        actionBreakdown: statistics.logsByAction,
        severityBreakdown: statistics.logsBySeverity,
        successRate: statistics.successRate,
      },
      logs: includeLogs ? logs : [],
      compliance: {
        hipaaCompliant: true,
        retentionPeriod: 2555, // 7 years in days
        dataIntegrity: true,
      },
    };

    return report;
  }

  /**
   * Generate patient access report
   */
  static async generatePatientAccessReport(
    patientId: string,
    startDate?: Date,
    endDate?: Date
  ): Promise<AuditReport> {
    const query: AuditLogQuery = {
      patientId,
      startDate: startDate || new Date(Date.now() - 90 * 24 * 60 * 60 * 1000), // Last 90 days
      endDate: endDate || new Date(),
      limit: 10000,
    };

    const logs = await AuditService.query(query);
    const statistics = await this.calculateStatistics(logs, query.startDate!, query.endDate!);

    return {
      reportId: randomUUID(),
      reportType: 'patient_access',
      generatedAt: new Date(),
      generatedBy: 'system',
      startDate: query.startDate!,
      endDate: query.endDate!,
      summary: {
        totalLogs: statistics.totalLogs,
        totalUsers: Object.keys(statistics.logsByUser).length,
        totalPatients: 1,
        actionBreakdown: statistics.logsByAction,
        severityBreakdown: statistics.logsBySeverity,
        successRate: statistics.successRate,
      },
      logs,
      compliance: {
        hipaaCompliant: true,
        retentionPeriod: 2555,
        dataIntegrity: true,
      },
    };
  }

  /**
   * Generate user activity report
   */
  static async generateUserActivityReport(
    userId: string,
    startDate?: Date,
    endDate?: Date
  ): Promise<AuditReport> {
    const query: AuditLogQuery = {
      userId,
      startDate: startDate || new Date(Date.now() - 30 * 24 * 60 * 60 * 1000), // Last 30 days
      endDate: endDate || new Date(),
      limit: 10000,
    };

    const logs = await AuditService.query(query);
    const statistics = await this.calculateStatistics(logs, query.startDate!, query.endDate!);

    return {
      reportId: randomUUID(),
      reportType: 'user_activity',
      generatedAt: new Date(),
      generatedBy: 'system',
      startDate: query.startDate!,
      endDate: query.endDate!,
      summary: {
        totalLogs: statistics.totalLogs,
        totalUsers: 1,
        totalPatients: Object.keys(statistics.logsByPatient).length,
        actionBreakdown: statistics.logsByAction,
        severityBreakdown: statistics.logsBySeverity,
        successRate: statistics.successRate,
      },
      logs,
      compliance: {
        hipaaCompliant: true,
        retentionPeriod: 2555,
        dataIntegrity: true,
      },
    };
  }

  /**
   * Export report to PDF
   */
  static async exportToPDF(
    report: AuditReport,
    outputPath: string
  ): Promise<string> {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    // Header
    doc.fontSize(20).text('HIPAA-Compliant Audit Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Report ID: ${report.reportId}`, { align: 'center' });
    doc.text(`Generated: ${report.generatedAt.toLocaleString()}`, { align: 'center' });
    doc.text(`Generated By: ${report.generatedBy}`, { align: 'center' });
    doc.text(
      `Period: ${report.startDate.toLocaleDateString()} - ${report.endDate.toLocaleDateString()}`,
      { align: 'center' }
    );
    doc.moveDown(2);

    // Summary
    doc.fontSize(16).text('Summary', { underline: true });
    doc.moveDown();
    doc.fontSize(12);
    doc.text(`Total Logs: ${report.summary.totalLogs}`);
    doc.text(`Total Users: ${report.summary.totalUsers}`);
    doc.text(`Total Patients: ${report.summary.totalPatients}`);
    doc.text(`Success Rate: ${(report.summary.successRate * 100).toFixed(2)}%`);
    doc.moveDown();

    // Action Breakdown
    doc.fontSize(14).text('Action Breakdown', { underline: true });
    doc.moveDown();
    for (const [action, count] of Object.entries(report.summary.actionBreakdown)) {
      doc.text(`${action}: ${count}`);
    }
    doc.moveDown();

    // Severity Breakdown
    doc.fontSize(14).text('Severity Breakdown', { underline: true });
    doc.moveDown();
    for (const [severity, count] of Object.entries(report.summary.severityBreakdown)) {
      doc.text(`${severity}: ${count}`);
    }
    doc.moveDown(2);

    // Compliance Information
    doc.fontSize(14).text('Compliance Information', { underline: true });
    doc.moveDown();
    doc.text(`HIPAA Compliant: ${report.compliance.hipaaCompliant ? 'Yes' : 'No'}`);
    doc.text(`Retention Period: ${report.compliance.retentionPeriod} days`);
    doc.text(`Data Integrity: ${report.compliance.dataIntegrity ? 'Verified' : 'Not Verified'}`);
    doc.moveDown(2);

    // Detailed Logs (if included)
    if (report.logs.length > 0) {
      doc.fontSize(16).text('Detailed Logs', { underline: true });
      doc.moveDown();

      report.logs.slice(0, 100).forEach((log, index) => {
        // New page every 10 logs
        if (index > 0 && index % 10 === 0) {
          doc.addPage();
        }

        doc.fontSize(10);
        doc.text(`[${index + 1}] ${log.timestamp.toLocaleString()}`, { continued: true });
        doc.text(` | ${log.actionType}`, { continued: true });
        doc.text(` | ${log.userId}`, { continued: true });
        if (log.patientId) {
          doc.text(` | Patient: ${log.patientId}`, { continued: true });
        }
        doc.text(` | ${log.severity}`, { continued: true });
        doc.text(` | ${log.success ? 'Success' : 'Failed'}`, { continued: true });
        doc.moveDown(0.5);
        doc.text(`   ${log.description}`, { indent: 20 });
        doc.moveDown();
      });

      if (report.logs.length > 100) {
        doc.moveDown();
        doc.text(`... and ${report.logs.length - 100} more logs (truncated for PDF)`, {
          italic: true,
        });
      }
    }

    // Footer
    doc.fontSize(8);
    doc.text(
      `This report contains sensitive audit information and should be handled according to HIPAA guidelines.`,
      { align: 'center', italic: true }
    );

    doc.end();

    return new Promise((resolve, reject) => {
      stream.on('finish', () => resolve(outputPath));
      stream.on('error', reject);
    });
  }

  /**
   * Export report to CSV
   */
  static async exportToCSV(report: AuditReport, outputPath: string): Promise<string> {
    const rows: string[] = [];

    // Header
    rows.push(
      'Timestamp,User ID,User Name,Action Type,Resource Type,Patient ID,Patient Name,Description,IP Address,Severity,Success,Error Message'
    );

    // Data rows
    for (const log of report.logs) {
      const row = [
        log.timestamp.toISOString(),
        log.userId || '',
        log.userName || '',
        log.actionType,
        log.resourceType,
        log.patientId || '',
        log.patientName || '',
        `"${log.description.replace(/"/g, '""')}"`,
        log.ipAddress || '',
        log.severity,
        log.success ? 'Yes' : 'No',
        log.errorMessage ? `"${log.errorMessage.replace(/"/g, '""')}"` : '',
      ];
      rows.push(row.join(','));
    }

    fs.writeFileSync(outputPath, rows.join('\n'), 'utf-8');
    return outputPath;
  }

  /**
   * Export report to JSON
   */
  static async exportToJSON(report: AuditReport, outputPath: string): Promise<string> {
    const json = JSON.stringify(report, null, 2);
    fs.writeFileSync(outputPath, json, 'utf-8');
    return outputPath;
  }

  /**
   * Calculate statistics from logs
   */
  private static async calculateStatistics(
    logs: AuditLogEntry[],
    startDate: Date,
    endDate: Date
  ): Promise<AuditStatistics> {
    const logsByAction: Record<string, number> = {};
    const logsByResource: Record<string, number> = {};
    const logsBySeverity: Record<string, number> = {};
    const logsByUser: Record<string, number> = {};
    const logsByPatient: Record<string, number> = {};
    let successfulLogs = 0;

    for (const log of logs) {
      logsByAction[log.actionType] = (logsByAction[log.actionType] || 0) + 1;
      logsByResource[log.resourceType] = (logsByResource[log.resourceType] || 0) + 1;
      logsBySeverity[log.severity] = (logsBySeverity[log.severity] || 0) + 1;

      if (log.userId) {
        logsByUser[log.userId] = (logsByUser[log.userId] || 0) + 1;
      }

      if (log.patientId) {
        logsByPatient[log.patientId] = (logsByPatient[log.patientId] || 0) + 1;
      }

      if (log.success) {
        successfulLogs++;
      }
    }

    // Calculate top users
    const topUsers = Object.entries(logsByUser)
      .map(([userId, count]) => ({
        userId,
        userName: logs.find((l) => l.userId === userId)?.userName || userId,
        count,
      }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 10);

    // Calculate top patients
    const topPatients = Object.entries(logsByPatient)
      .map(([patientId, count]) => ({
        patientId,
        patientName: logs.find((l) => l.patientId === patientId)?.patientName || patientId,
        count,
      }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 10);

    return {
      totalLogs: logs.length,
      logsByAction,
      logsByResource,
      logsBySeverity,
      logsByUser,
      logsByPatient,
      successRate: logs.length > 0 ? successfulLogs / logs.length : 0,
      topUsers,
      topPatients,
    };
  }
}
