/* eslint-disable */
/** AUTO-GENERATED by scripts/build-facts-snapshot.mjs — do not edit by hand */
export type FactsPricingSku =
  | "meetGreet"
  | "initialEvaluation"
  | "nonControlledFollowUp"
  | "controlledFollowUp";

export interface FactsPricingRow {
  label: string;
  amount: number;
  display: string;
  period: string;
  description: string;
}

export interface FactsProviderRow {
  slug: string;
  name: string;
  displayName: string;
  givenName: string;
  familyName: string;
  credentials: string[];
  specialtyChips: string[];
  role: string;
  profilePath: string;
  profileUrl: string;
  statesLicensed: string[];
  statesService: string[];
  stateAbbreviations: string[];
}

export interface FactsInsurance {
  acceptsInsurance: boolean;
  summary: string;
  fsaHsaNote: string;
  pricingPath: string;
  fsaHsaPath: string;
  pricingUrl: string;
  fsaHsaUrl: string;
  channelNote: string;
}

export interface FactsContact {
  phoneDisplay: string;
  phoneHref: string;
  email: string;
  emailHref: string;
}

export interface FactsServiceLine {
  key: string;
  label: string;
  aliases: string[];
  path: string;
  url: string;
  indexTitle: string;
  staffBlurb: string;
}

export interface FactsBookingLink {
  key: string;
  label: string;
  redirectPath: string;
  redirectUrl: string;
  directUrl: string;
  note: string;
}

export interface FactsCancellation {
  channel: string;
  noShowFeeAmount: number;
  noShowFeeDisplay: string;
  noShowSummary: string;
  lateCancelStatus: string;
  lateCancelSummary: string;
  channelNote: string;
  retiredLegacyAmounts: string[];
}

export interface FactsHours {
  hasFixedPracticeHours: boolean;
  summary: string;
  staffNote: string;
}

export interface FactsSnapshot {
  generated: string;
  source: string;
  availableServiceStates: string[];
  pricing: Record<FactsPricingSku, FactsPricingRow> & { path: string };
  providers: FactsProviderRow[];
  insurance: FactsInsurance;
  contact: FactsContact;
  services: FactsServiceLine[];
  booking: Record<string, FactsBookingLink>;
  cancellation: FactsCancellation;
  hours: FactsHours;
  baseUrl: string;
}

export const FACTS_SNAPSHOT: FactsSnapshot = {
  "generated": "2026-09-03",
  "source": "apps/siya-health site-standards + providers + provider-canonical + homepage-trust-metrics + providers-core + service-index.json + founder-locked cancel/hours facts",
  "availableServiceStates": [
    "California",
    "Texas",
    "Pennsylvania",
    "Florida"
  ],
  "pricing": {
    "meetGreet": {
      "label": "Meet & Greet",
      "amount": 0,
      "display": "Free",
      "period": "",
      "description": "Short, free, non-clinical conversation to understand needs and choose a next step. Not a medical visit, diagnosis, or treatment. No medication prescribed."
    },
    "initialEvaluation": {
      "label": "Initial Evaluation",
      "amount": 149,
      "display": "$149",
      "period": "one-time visit",
      "description": "Structured clinician visit: history, goals, and a clear plan. Applies to ADHD, weight, metabolic, primary care, and telehealth pathways."
    },
    "nonControlledFollowUp": {
      "label": "Non-Controlled Medication Follow-Up",
      "amount": 79,
      "display": "$79",
      "period": "/month",
      "description": "Ongoing follow-up for non-controlled medications, lifestyle plans, labs review, and care coordination when appropriate."
    },
    "controlledFollowUp": {
      "label": "Controlled Medication Follow-Up",
      "amount": 149,
      "display": "$149",
      "period": "/month",
      "description": "Ongoing follow-up when controlled medications are part of your plan—including monitoring, dose adjustments, and safety checks per state law."
    },
    "path": "/pricing"
  },
  "providers": [
    {
      "slug": "dr-sneh-pandey",
      "name": "Dr. Sneh Pandey, MD",
      "displayName": "Dr. Sneh Pandey, MD",
      "givenName": "Sneh",
      "familyName": "Pandey",
      "credentials": [
        "MD"
      ],
      "specialtyChips": [
        "Internal Medicine",
        "Obesity Medicine",
        "ADHD-CCSP",
        "Medical Director",
        "Board Certified Internal Medicine"
      ],
      "role": "Medical Director · Internal Medicine Physician",
      "profilePath": "/providers/dr-sneh-pandey",
      "profileUrl": "https://www.siya.health/providers/dr-sneh-pandey",
      "statesLicensed": [
        "California",
        "Pennsylvania",
        "Florida"
      ],
      "statesService": [
        "California",
        "Pennsylvania",
        "Florida"
      ],
      "stateAbbreviations": [
        "CA",
        "PA",
        "FL"
      ]
    },
    {
      "slug": "dr-vanessa-urbina",
      "name": "Dr. Vanessa Urbina, MD",
      "displayName": "Dr. Vanessa Urbina, MD",
      "givenName": "Vanessa",
      "familyName": "Urbina",
      "credentials": [
        "MD"
      ],
      "specialtyChips": [
        "Family Medicine",
        "Primary Care",
        "ADHD",
        "Lifestyle Medicine"
      ],
      "role": "Family Medicine Physician",
      "profilePath": "/providers/dr-vanessa-urbina",
      "profileUrl": "https://www.siya.health/providers/dr-vanessa-urbina",
      "statesLicensed": [
        "Florida"
      ],
      "statesService": [
        "Florida"
      ],
      "stateAbbreviations": [
        "FL"
      ]
    },
    {
      "slug": "dr-natasha-desai",
      "name": "Dr. Natasha Desai, MD",
      "displayName": "Dr. Natasha Desai, MD",
      "givenName": "Natasha",
      "familyName": "Desai",
      "credentials": [
        "MD"
      ],
      "specialtyChips": [
        "Family Medicine",
        "ADHD-CCSP",
        "American Board of Family Medicine"
      ],
      "role": "Family Medicine Physician",
      "profilePath": "/providers/dr-natasha-desai",
      "profileUrl": "https://www.siya.health/providers/dr-natasha-desai",
      "statesLicensed": [
        "Texas",
        "Florida",
        "Pennsylvania"
      ],
      "statesService": [
        "Texas",
        "Florida",
        "Pennsylvania"
      ],
      "stateAbbreviations": [
        "TX",
        "FL",
        "PA"
      ]
    },
    {
      "slug": "dr-swati-pandey",
      "name": "Dr. Swati Pandey, MD",
      "displayName": "Dr. Swati Pandey, MD",
      "givenName": "Swati",
      "familyName": "Pandey",
      "credentials": [
        "MD"
      ],
      "specialtyChips": [
        "Internal Medicine",
        "ADHD-CCSP",
        "Mental Health Care"
      ],
      "role": "Internal Medicine Physician",
      "profilePath": "/providers/dr-swati-pandey",
      "profileUrl": "https://www.siya.health/providers/dr-swati-pandey",
      "statesLicensed": [
        "Pennsylvania"
      ],
      "statesService": [
        "Pennsylvania"
      ],
      "stateAbbreviations": [
        "PA"
      ]
    },
    {
      "slug": "megan-wunderlich",
      "name": "Megan Wunderlich, FNP-C",
      "displayName": "Megan Wunderlich, FNP-C",
      "givenName": "Megan",
      "familyName": "Wunderlich",
      "credentials": [
        "MSN",
        "APRN",
        "FNP-C"
      ],
      "specialtyChips": [
        "FNP-C",
        "Mental Health",
        "Family Medicine"
      ],
      "role": "Family Nurse Practitioner",
      "profilePath": "/providers/megan-wunderlich",
      "profileUrl": "https://www.siya.health/providers/megan-wunderlich",
      "statesLicensed": [
        "Pennsylvania"
      ],
      "statesService": [
        "Pennsylvania"
      ],
      "stateAbbreviations": [
        "PA"
      ]
    },
    {
      "slug": "wendy-delgado",
      "name": "Wendy Delgado, PA-C",
      "displayName": "Wendy Delgado, PA-C",
      "givenName": "Wendy",
      "familyName": "Delgado",
      "credentials": [
        "PA-C"
      ],
      "specialtyChips": [
        "PA-C",
        "ADHD",
        "Women's Health",
        "Weight Loss",
        "Telehealth",
        "NCCPA Certified PA"
      ],
      "role": "Physician Associate · Adult telehealth generalist",
      "profilePath": "/providers/wendy-delgado",
      "profileUrl": "https://www.siya.health/providers/wendy-delgado",
      "statesLicensed": [
        "California",
        "Texas",
        "Pennsylvania",
        "Florida"
      ],
      "statesService": [
        "California",
        "Texas",
        "Pennsylvania",
        "Florida"
      ],
      "stateAbbreviations": [
        "CA",
        "TX",
        "PA",
        "FL"
      ]
    }
  ],
  "insurance": {
    "acceptsInsurance": false,
    "summary": "Siya Health does not accept insurance. We offer transparent cash pricing today. Many patients use FSA or HSA funds for eligible services — confirm with your plan administrator; Siya provides itemized receipts. Insurance-based options may be added later.",
    "fsaHsaNote": "FSA/HSA: clinical evaluation and many visit fees may qualify as medical expenses when documented — plan administrator decides. Medication is usually paid at the pharmacy under separate pharmacy/plan rules.",
    "pricingPath": "/pricing",
    "fsaHsaPath": "/answers/fsa-hsa-adhd-evaluation",
    "pricingUrl": "https://www.siya.health/pricing",
    "fsaHsaUrl": "https://www.siya.health/answers/fsa-hsa-adhd-evaluation",
    "channelNote": "This is siya.health direct cash-pay — not Klarity marketplace insurance. Do not mix Klarity insured-patient rules with this answer."
  },
  "contact": {
    "phoneDisplay": "(215) 445-1244",
    "phoneHref": "tel:+12154451244",
    "email": "care@siya.health",
    "emailHref": "mailto:care@siya.health"
  },
  "services": [
    {
      "key": "adhd",
      "label": "Adult ADHD care",
      "aliases": [
        "adhd",
        "adult adhd",
        "adhd care",
        "adhd evaluation",
        "adhd diagnosis",
        "focus care"
      ],
      "path": "/adhd-care",
      "url": "https://www.siya.health/adhd-care",
      "indexTitle": "Adult ADHD Diagnosis Online — Same-Week Evaluation",
      "staffBlurb": "Physician-led adult ADHD evaluation and follow-up via telehealth — structured history, validated tools as appropriate, comorbidity screening, and a documented plan. Diagnosis does not guarantee medication."
    },
    {
      "key": "weight",
      "label": "Weight loss / metabolic health",
      "aliases": [
        "weight",
        "weight loss",
        "metabolic",
        "glp-1",
        "glp1",
        "semaglutide",
        "ozempic"
      ],
      "path": "/weight-loss-metabolic-health",
      "url": "https://www.siya.health/weight-loss-metabolic-health",
      "indexTitle": "Provider-Guided Medical Weight Loss",
      "staffBlurb": "Provider-guided medical weight-loss and metabolic care, including GLP-1 or other options when clinically appropriate — not a meds-only storefront."
    },
    {
      "key": "primary",
      "label": "Primary & urgent care",
      "aliases": [
        "primary",
        "primary care",
        "urgent care",
        "sick visit"
      ],
      "path": "/primary-urgent-care",
      "url": "https://www.siya.health/primary-urgent-care",
      "indexTitle": "Primary & Urgent Care Telehealth",
      "staffBlurb": "Virtual primary and urgent-style adult visits — wellness, chronic care support, preventive lab review, and clear follow-up plans. Not an emergency room."
    },
    {
      "key": "telehealth",
      "label": "Telehealth",
      "aliases": [
        "telehealth",
        "virtual care",
        "online visit",
        "video visit"
      ],
      "path": "/telehealth",
      "url": "https://www.siya.health/telehealth",
      "indexTitle": "Virtual Medical Care | Siya Health Telehealth",
      "staffBlurb": "Siya Health delivers physician-led virtual medical care (telehealth) in licensed states, with documented visits and secure messaging pathways."
    },
    {
      "key": "mens",
      "label": "Men's health",
      "aliases": [
        "men's health",
        "mens health",
        "testosterone",
        "trt",
        "men's"
      ],
      "path": "/mens-health-longevity",
      "url": "https://www.siya.health/mens-health-longevity",
      "indexTitle": "Men's Health & Longevity",
      "staffBlurb": "Physician-led men's health telehealth — testosterone evaluation, ED support, metabolic/longevity planning — not testosterone-first marketing."
    },
    {
      "key": "womens",
      "label": "Women's health",
      "aliases": [
        "women's health",
        "womens health",
        "midlife",
        "perimenopause",
        "pcos",
        "women's"
      ],
      "path": "/womens-health",
      "url": "https://www.siya.health/womens-health",
      "indexTitle": "Women's health",
      "staffBlurb": "Women's health telehealth for PCOS, perimenopause, thyroid/metabolic concerns, ADHD in women, and preventive care."
    },
    {
      "key": "labs",
      "label": "Labs & blood tests",
      "aliases": [
        "labs",
        "lab",
        "blood test",
        "bloodwork",
        "lab testing"
      ],
      "path": "/labs",
      "url": "https://www.siya.health/labs",
      "indexTitle": "Labs & Blood Tests | Transparent Direct-Pay Testing",
      "staffBlurb": "Transparent direct-pay lab testing (thyroid, blood sugar, vitamins, iron, metabolic/preventive) with physician guidance available. Labs alone do not diagnose ADHD."
    },
    {
      "key": "prescriptions",
      "label": "Prescriptions / pharmacy pathway",
      "aliases": [
        "prescriptions",
        "prescription",
        "rx",
        "pharmacy",
        "refill page"
      ],
      "path": "/prescriptions",
      "url": "https://www.siya.health/prescriptions",
      "indexTitle": "Prescriptions",
      "staffBlurb": "Provider-reviewed prescriptions through Siya telehealth when clinically appropriate. Availability varies by state and indication — never promise a specific controlled substance."
    }
  ],
  "booking": {
    "meetGreet": {
      "key": "meetGreet",
      "label": "Free Meet & Greet",
      "redirectPath": "/redirect/meet-greet",
      "redirectUrl": "https://www.siya.health/redirect/meet-greet",
      "directUrl": "https://book.carepatron.com/Siya-Health?p=X9PN3zKZR22FpD8jVPKsOA&i=kkarJfxH",
      "note": "Primary patient intro CTA. Free, non-clinical. Prefer site redirect for tracking."
    },
    "spruce": {
      "key": "spruce",
      "label": "Spruce secure medical chat",
      "redirectPath": "/redirect/chat",
      "redirectUrl": "https://www.siya.health/redirect/chat",
      "directUrl": "https://spruce.care/siyahealth",
      "note": "Private clinical messaging via Spruce. Prefer /redirect/chat for ads tracking."
    },
    "evaluation": {
      "key": "evaluation",
      "label": "ADHD / clinical evaluation booking",
      "redirectPath": "/redirect/adhd-evaluation",
      "redirectUrl": "https://www.siya.health/redirect/adhd-evaluation",
      "directUrl": "https://book.carepatron.com/Siya-Health?p=X9PN3zKZR22FpD8jVPKsOA&i=bxrKBOuk",
      "note": "Paid evaluation CarePatron slot ($149 canonical). Prefer /redirect/adhd-evaluation."
    },
    "defaultBooking": {
      "key": "defaultBooking",
      "label": "Default booking link (Meet & Greet)",
      "redirectPath": "/redirect/meet-greet",
      "redirectUrl": "https://www.siya.health/redirect/meet-greet",
      "directUrl": "https://book.carepatron.com/Siya-Health?p=X9PN3zKZR22FpD8jVPKsOA&i=kkarJfxH",
      "note": "BOOKING_LINK currently equals Meet & Greet."
    }
  },
  "cancellation": {
    "channel": "siya.health_direct",
    "noShowFeeAmount": 50,
    "noShowFeeDisplay": "$50",
    "noShowSummary": "Do not waive or refund in chat — escalate Billing lead for disputes.",
    "lateCancelStatus": "pending_founder",
    "lateCancelSummary": "Late-cancel amount is not locked — escalate Billing lead; do not invent a fee (legacy $40/$79 retired).",
    "channelNote": "Klarity-booked visits use klarity-billing-cancellation — not the direct $50 no-show fee.",
    "retiredLegacyAmounts": [
      "$40",
      "$79 full no-show (legacy conflict)",
      "full appointment fee as default no-show"
    ]
  },
  "hours": {
    "hasFixedPracticeHours": false,
    "summary": "Siya Health does not publish fixed practice-wide business hours. Availability is provider-specific and set weekly in the EHR. Direct patients to check open slots at scheduling / booking — do not invent or imply a standard Monday–Friday hours string.",
    "staffNote": "If a patient needs a human for booking help, use care@siya.health or (215) 445-1244 — still without inventing hours."
  },
  "baseUrl": "https://www.siya.health"
} as FactsSnapshot;
