/** Human-readable labels for quiz analytics (primary tag buckets). */
const MAP: Record<string, string> = {
  general: "General",
  "public-trust": "Public trust & information sharing",
  ehr: "EHRs & health information exchange",
  withholding: "Patients withholding information",
  "hipaa-purpose": "What HIPAA is for",
  "rules-overview": "HIPAA rules overview",
  omnibus: "Omnibus Rule",
  ba: "Business associates (overview)",
  hitech: "HITECH Act",
  penalties: "Penalties & enforcement tiers",
  enforcement: "Enforcement (OCR)",
  ocr: "Office for Civil Rights (OCR)",
  scope: "Who must comply (CE / BA)",
  "ce-types": "Types of covered entities",
  "ce-scope": "When a provider is a CE",
  "ba-definition": "Business associate definition",
  "ba-examples": "BA vs non-BA examples",
  baa: "Business associate agreements",
  "baa-exceptions": "When BAAs may not be required",
  "ace-ohca": "Affiliated CE & OHCA",
  "multi-function": "CEs with multiple functions",
  "phi-forms": "Forms of PHI (oral, paper, electronic)",
  "phi-examples": "What counts as PHI",
  "de-id": "De-identification",
  "re-id": "Re-identification codes",
  "limited-data-set": "Limited data sets",
  "privacy-rule-role": "Privacy Rule purpose",
  "hhs-disclosure": "Disclosures to HHS",
  incidental: "Incidental disclosures",
  "minimum-necessary": "Minimum necessary",
  "minimum-necessary-exc": "Minimum necessary exceptions",
  "admin-reqs": "Privacy administrative requirements",
  preemption: "Federal vs state law",
  permissions: "Permitted uses & disclosures",
  "access-right": "Right of access",
  drs: "Designated record set",
  "access-timing": "Access timelines",
  "access-fees": "Fees for access",
  "personal-rep": "Personal representatives",
  npp: "Notice of Privacy Practices",
  amend: "Right to amend",
  "accounting-exc": "Accounting of disclosures — exceptions",
  restrictions: "Restriction requests (§164.522)",
  complaints: "Complaints & OCR processes",
  "security-rule-scope": "Security Rule scope",
  "ephi-scope": "ePHI vs other PHI",
  flexibility: "Security Rule flexibility",
  "risk-analysis": "Risk analysis & assessment",
  "safeguard-types": "Types of safeguards",
  standards: "Standards vs implementation specs",
  addressable: "Required vs addressable",
  "admin-incident": "Incident procedures",
  physical: "Physical safeguards",
  "unique-id": "Unique user identification",
  "policy-review": "Policy review cadence",
  "breach-def": "What is a breach",
  "notification-exc": "When notification may not apply",
  "who-notify": "Who receives breach notice",
  timing: "Breach notification timing",
  "hhs-timing": "Notifying HHS",
  "burden-proof": "Breach burden of proof",
  "breach-admin": "Breach notification admin requirements",
  "ocr-role": "OCR’s role",
  investigation: "Investigations",
  "audit-types": "Audit types",
  "audit-selection": "Who may be audited",
  "audit-scope": "Audit program scope",
  "compliance-review": "Compliance reviews",
  "penalty-factors": "Civil penalty factors",
  "penalty-amounts": "Penalty dollar amounts (verify current)",
  criminal: "Criminal penalties",
  transactions: "Standard transactions",
  "code-sets": "Code sets",
  npi: "National Provider Identifier (NPI)",
};

export function topicLabel(tag: string): string {
  return MAP[tag] ?? tag.replace(/-/g, " ");
}
