/* eslint-disable */
/** AUTO-GENERATED by scripts/build-workspace-kb.mjs — do not edit by hand */
import type { WorkspaceKbEntry } from "./workspace-kb.types";

export const GENERATED_WORKSPACE_KB: WorkspaceKbEntry[] = [
  {
    "id": "escalation-pathways",
    "category": "operations",
    "title": "Escalation pathways (all departments)",
    "keywords": [
      "escalate",
      "escalation",
      "supervisor",
      "who to call",
      "help",
      "billing",
      "privacy",
      "clinical",
      "IT"
    ],
    "body": "Give the escalation order clearly. Remind: no PHI in Siya Assistant chat; no clinical advice; billing promises require billing lead. Offer Training link for HIPAA certification.",
    "links": [
      {
        "label": "- label: HIPAA certification course",
        "href": "/training"
      }
    ]
  },
  {
    "id": "hipaa-breach",
    "category": "legal_compliance",
    "title": "Suspected breach or privacy incident",
    "keywords": [
      "breach",
      "phi",
      "unauthorized",
      "privacy",
      "incident",
      "background",
      "video"
    ],
    "body": "Always escalate to Privacy Officer; never assess breach status in chat. Link to Training breach module. No patient identifiers in assistant.",
    "links": [
      {
        "label": "- label: Breach training module",
        "href": "/module/breach"
      }
    ],
    "escalate": "Privacy Officer immediately"
  },
  {
    "id": "internal-assistant-guardrails",
    "category": "ai_strategy",
    "title": "Internal assistant (Siya) — guardrails",
    "keywords": [
      "siya assistant",
      "chatbot",
      "internal ai",
      "phi",
      "guardrails",
      "knowledge base",
      "retrieval"
    ],
    "body": "You are a workforce helper for all functions (ops, marketing, HR, eng, clinical coordination) — not a clinician. Prefer SOP and AI Context sections. Always show escalation contacts when relevant."
  },
  {
    "id": "billing-late-cancel",
    "category": "operations",
    "title": "Late cancellation and refunds",
    "keywords": [
      "late cancel",
      "cancellation",
      "refund",
      "same day",
      "billing"
    ],
    "body": "Never authorize refunds. Point to written policy and billing lead. Suggest documenting cancel time.",
    "escalate": "Billing lead"
  },
  {
    "id": "daily-payment-check",
    "category": "operations",
    "title": "Daily payment check (before visits)",
    "keywords": [
      "payment",
      "zoho",
      "books",
      "billing",
      "pre-auth",
      "appointment",
      "daily task"
    ],
    "body": "Describe the Zoho → appointment → EHR verification loop. Do not access live patient accounts in chat. Escalate payment disputes to billing lead."
  },
  {
    "id": "third-party-caller",
    "category": "legal_compliance",
    "title": "Family or third party asking about care or charges",
    "keywords": [
      "mom",
      "parent",
      "family",
      "third party",
      "verify",
      "authorization"
    ],
    "body": "Never suggest sharing account details with unverified callers. Escalate to Privacy Officer when authorization is unclear.",
    "escalate": "Privacy Officer / supervisor"
  },
  {
    "id": "homepage-cta-meet-and-greet",
    "category": "decisions",
    "title": "Homepage primary CTA — Book Free Meet & Greet",
    "keywords": [
      "cta",
      "homepage",
      "meet and greet",
      "zocdoc",
      "booking"
    ],
    "body": "When staff ask why we don't lead with Zocdoc or alternate CTAs on the homepage, explain trust/friction rationale and point to SIYA-STANDARDS CTA section—not folklore. Standardize the primary homepage CTA to **Book Free Meet & Greet** (per SIYA-STANDARDS CTA hierarchy), not third-party marketplace checkout as the hero action. Highest trust and lower friction for physician-led telehealth positioning; keeps booking on owned flows."
  },
  {
    "id": "chat-review-sla",
    "category": "clinical_operations",
    "title": "Patient portal chat — response SLAs",
    "keywords": [
      "chat",
      "portal",
      "message",
      "24 hour",
      "routine",
      "clinical",
      "escalate provider"
    ],
    "body": "Emphasize 24h for non-clinical, immediate provider escalation for clinical. Never give medical advice in assistant or chat without provider direction."
  },
  {
    "id": "telehealth-privacy-background",
    "category": "clinical_operations",
    "title": "Telehealth — privacy and background viewers",
    "keywords": [
      "telehealth",
      "video",
      "background",
      "camera",
      "private"
    ],
    "body": "Explain pause-and-reposition workflow. Escalate to Privacy Officer if PHI may have been disclosed.",
    "escalate": "Privacy Officer if PHI exposed"
  },
  {
    "id": "brand-entities-voice",
    "category": "brand",
    "title": "Entities, voice, and positioning (canonical)",
    "keywords": [
      "brand",
      "voice",
      "siya health inc",
      "pllc",
      "telehealth",
      "physician-led",
      "health guides"
    ],
    "body": "Summarize entity split and voice rules. For exact pricing/states, defer to site standards — do not guess. Internal staff asking for ad copy should also read Marketing OS content QA topic."
  },
  {
    "id": "content-qa-checklist",
    "category": "marketing_os",
    "title": "Pre-publish content QA (10 checks)",
    "keywords": [
      "marketing",
      "content",
      "QA",
      "publish",
      "disclaimer",
      "CTA",
      "seo",
      "editorial"
    ],
    "body": "Point marketers to CONTENT-QA-CHECKLIST and Brand OS. Do not invent pricing or state lists — canonical values live in site standards. Company voice only unless exec requests founder voice."
  },
  {
    "id": "hipaa-training-cert",
    "category": "legal_compliance",
    "title": "HIPAA certification course (staff)",
    "keywords": [
      "course",
      "certification",
      "certificate",
      "training",
      "quiz",
      "hipaa"
    ],
    "body": "Direct staff to `/training` for certification; chat answers are supplements, not a substitute for completing modules.",
    "links": [
      {
        "label": "- label: Open training",
        "href": "/training"
      }
    ]
  },
  {
    "id": "amcare-os-overview",
    "category": "technology",
    "title": "AmCare OS — modular ops stack",
    "keywords": [
      "amcare",
      "siyaos",
      "monorepo",
      "staff dashboard",
      "patient management",
      "operations hub",
      "audit",
      "hipaa"
    ],
    "body": "Describe AmCare OS at architecture level only — no credentials, no internal URLs with secrets. Point developers to README and audit package. Future CAPR.AI inherits patterns, not Siya-only hacks."
  }
];
