/**
 * DRAFT — HIPAA bank expansion sample (NOT in the live exam bank).
 *
 * Do not import into ALL_QUESTIONS / questionBank until human review clears.
 * Reviewers: Sneha (compliance accuracy) and/or Sonu (MA clarity).
 *
 * See: docs/HIPAA-BANK-EXPANSION-DESIGN.md
 */
import type { Question } from "@/lib/types";

export type DraftHipaaExpansionItem = Question & {
  parentConceptId: string;
  variantMove: "role" | "channel" | "setting" | "boundary" | "actor" | "temporal" | "failure";
  reviewStatus: "draft";
};

/** ~25 sample items — spread across modules. All reviewStatus: draft. */
export const HIPAA_BANK_EXPANSION_DRAFT_V1: DraftHipaaExpansionItem[] = [
  {
    id: "draft-v1-001",
    parentConceptId: "t-1",
    variantMove: "setting",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "intro",
    tags: ["public-trust", "ehr", "draft-expansion"],
    difficulty: 1,
    type: "scenario",
    prompt:
      "A patient tells an MA they will not use the patient portal because they do not trust how the clinic protects health information. Based on the training pattern about perceived protections, this patient is ________ likely to support electronic health records and health information exchange.",
    options: [
      { key: "a", text: "More (likely)" },
      { key: "b", text: "Less (likely)" },
    ],
    correctKey: "b",
    explanation:
      "Weaker perceived protections → lower support for EHRs/HIE (same causal pattern as the parent item; portal channel is the variant).",
    distractorHints: { a: "Trust concerns reduce, not increase, support for digital sharing." },
  },
  {
    id: "draft-v1-002",
    parentConceptId: "t-1",
    variantMove: "role",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "intro",
    tags: ["public-trust", "withholding", "draft-expansion"],
    difficulty: 1,
    type: "tf",
    prompt:
      "True or False: When patients believe protections for their health information are weak, they may be more likely to withhold clinically important information from a provider.",
    options: [
      { key: "a", text: "True" },
      { key: "b", text: "False" },
    ],
    correctKey: "a",
    explanation: "Training links weak perceived protection to withholding information as well as lower EHR/HIE support.",
  },
  {
    id: "draft-v1-003",
    parentConceptId: "t-8",
    variantMove: "actor",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "ce-ba",
    tags: ["scope", "ba", "draft-expansion"],
    difficulty: 1,
    type: "mcq",
    prompt:
      "A contracted cleaning company staff member occasionally sees papers on a desk while emptying trash but has no job duties involving PHI. Under the training distinction used on your exam, this person is best described as:",
    options: [
      { key: "a", text: "A business associate because they can see PHI on site" },
      { key: "b", text: "Not a business associate based on incidental exposure alone" },
      { key: "c", text: "A covered entity" },
      { key: "d", text: "A hybrid entity" },
    ],
    correctKey: "b",
    explanation: "Incidental exposure without PHI functions does not by itself create BA status (classic training distractor).",
    distractorHints: {
      a: "Seeing PHI incidentally is not the same as performing PHI functions for the CE.",
      c: "CEs are plans, clearinghouses, or covered providers — not incidental vendors.",
      d: "Hybrid entity is an organizational designation, not a vendor label.",
    },
  },
  {
    id: "draft-v1-004",
    parentConceptId: "t-8",
    variantMove: "actor",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "ce-ba",
    tags: ["scope", "ba", "draft-expansion"],
    difficulty: 1,
    type: "mcq",
    prompt:
      "Which arrangement is most clearly BA-like under your training materials?",
    options: [
      { key: "a", text: "A claims TPA that receives and processes PHI for the health plan" },
      { key: "b", text: "A food delivery driver who never handles clinical records" },
      { key: "c", text: "A patient waiting in the lobby" },
      { key: "d", text: "A visitor who walks past a closed chart room door" },
    ],
    correctKey: "a",
    explanation: "BA creates/receives/maintains/transmits PHI for or on behalf of a CE; TPA claims processing is the clear match.",
  },
  {
    id: "draft-v1-005",
    parentConceptId: "t-8",
    variantMove: "boundary",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "ce-ba",
    tags: ["scope", "baa", "draft-expansion"],
    difficulty: 2,
    type: "tf",
    prompt:
      "True or False: Before a covered entity discloses PHI to a business associate to perform services involving PHI, written assurance (typically a BAA) is generally required.",
    options: [
      { key: "a", text: "True" },
      { key: "b", text: "False" },
    ],
    correctKey: "a",
    explanation: "BAA / written assurance before PHI disclosure to a BA is a core CE/BA training point.",
  },
  {
    id: "draft-v1-006",
    parentConceptId: "t-18",
    variantMove: "channel",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "phi",
    tags: ["phi-forms", "draft-expansion"],
    difficulty: 1,
    type: "mcq",
    prompt:
      "An MA discusses a patient’s diagnosis with the patient on a phone call. That oral conversation can contain:",
    options: [
      { key: "a", text: "Only “notes,” not PHI, because it was not written down" },
      { key: "b", text: "PHI — HIPAA protects health information in electronic, paper, or oral form" },
      { key: "c", text: "ePHI only, because phones are electronic" },
      { key: "d", text: "Nothing regulated, if no medical record number was spoken" },
    ],
    correctKey: "b",
    explanation: "PHI is medium-neutral; oral disclosures are still PHI when identifiers + health info apply.",
  },
  {
    id: "draft-v1-007",
    parentConceptId: "t-18",
    variantMove: "setting",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "phi",
    tags: ["phi-forms", "ephi", "draft-expansion"],
    difficulty: 1,
    type: "tf",
    prompt:
      "True or False: A clinic’s electronic chart note is ePHI, and the Security Rule’s safeguards focus on electronic PHI — while the Privacy Rule still applies to PHI more broadly (including paper and oral).",
    options: [
      { key: "a", text: "True" },
      { key: "b", text: "False" },
    ],
    correctKey: "a",
    explanation: "Security Rule → ePHI safeguards; Privacy Rule → PHI use/disclosure and rights across media.",
  },
  {
    id: "draft-v1-008",
    parentConceptId: "t-19",
    variantMove: "boundary",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "phi",
    tags: ["phi-examples", "draft-expansion"],
    difficulty: 1,
    type: "mcq",
    prompt:
      "Which is the best example of PHI in an MA workflow?",
    options: [
      { key: "a", text: "A public hospital’s street address printed on a brochure with no patient names" },
      { key: "b", text: "A patient’s name plus their ADHD medication list in a portal message" },
      { key: "c", text: "A weather report emailed to the whole clinic staff" },
      { key: "d", text: "A blank appointment slot with no patient attached" },
    ],
    correctKey: "b",
    explanation: "PHI pairs health information with an individual identifier (here name + medication list).",
  },
  {
    id: "draft-v1-009",
    parentConceptId: "t-23",
    variantMove: "boundary",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "privacy",
    tags: ["privacy-rule-role", "draft-expansion"],
    difficulty: 1,
    type: "mcq",
    prompt:
      "An MA is asked what the Privacy Rule primarily does. The best answer is:",
    options: [
      { key: "a", text: "It only sets encryption standards for laptops" },
      { key: "b", text: "It limits PHI use/disclosure and establishes individual rights regarding PHI" },
      { key: "c", text: "It requires criminal prosecution by OCR for every complaint" },
      { key: "d", text: "It applies only to paper charts, not electronic records" },
    ],
    correctKey: "b",
    explanation: "Core Privacy Rule role in the outline; encryption/safeguards are Security Rule territory.",
  },
  {
    id: "draft-v1-010",
    parentConceptId: "t-24",
    variantMove: "role",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "privacy",
    tags: ["permitted-disclosures", "draft-expansion"],
    difficulty: 2,
    type: "scenario",
    prompt:
      "OCR requests records from a covered entity as part of a compliance review. Under your training materials, disclosing the needed PHI to HHS for that review is generally:",
    options: [
      { key: "a", text: "Prohibited unless the patient signs a new authorization first" },
      { key: "b", text: "A permitted disclosure pathway without that authorization requirement" },
      { key: "c", text: "Allowed only if the BA signs instead of the CE" },
      { key: "d", text: "Allowed only for ePHI, never paper" },
    ],
    correctKey: "b",
    explanation: "Parent item: CE may disclose PHI to HHS when required for review without individual authorization.",
  },
  {
    id: "draft-v1-011",
    parentConceptId: "t-30",
    variantMove: "boundary",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "rights",
    tags: ["permissions", "authorization", "draft-expansion"],
    difficulty: 2,
    type: "mcq",
    prompt:
      "An MA wants to email a patient’s full chart to the patient’s employer “because the patient asked verbally in the waiting room.” The safest training-aligned next step is:",
    options: [
      { key: "a", text: "Send it immediately — verbal ask always replaces authorization" },
      { key: "b", text: "Treat employer disclosure as outside routine care pathways and follow authorization / policy requirements before sending" },
      { key: "c", text: "Post the chart to social media if the patient is in a hurry" },
      { key: "d", text: "Send only if the employer is also a covered entity" },
    ],
    correctKey: "b",
    explanation:
      "Uses/disclosures generally need permission except permitted uses/disclosures; employer disclosure is a classic authorization scenario, not TPO casually.",
  },
  {
    id: "draft-v1-012",
    parentConceptId: "t-31",
    variantMove: "channel",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "rights",
    tags: ["access", "draft-expansion"],
    difficulty: 2,
    type: "scenario",
    prompt:
      "A patient messages the portal: “Send me a copy of my lab results from last month.” The Right to Access primarily gives the individual the right to ________, and gives the provider authority to ________ (within the rule’s framework).",
    options: [
      { key: "a", text: "Delete all clinic backups; refuse any copy" },
      { key: "b", text: "Inspect and obtain a copy of PHI; provide access as required under the access rules" },
      { key: "c", text: "Demand cash payment from OCR; ignore the request" },
      { key: "d", text: "Authorize unlimited marketing uses; sell the record" },
    ],
    correctKey: "b",
    explanation: "Access right = individual inspect/obtain copy; provider must provide access per the rule (parent item pattern).",
  },
  {
    id: "draft-v1-013",
    parentConceptId: "t-31",
    variantMove: "temporal",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "rights",
    tags: ["access", "draft-expansion"],
    difficulty: 2,
    type: "tf",
    prompt:
      "True or False: A patient’s right to access their PHI generally continues to matter after the visit is over — it is not limited to “only while they are sitting in the exam room.”",
    options: [
      { key: "a", text: "True" },
      { key: "b", text: "False" },
    ],
    correctKey: "a",
    explanation: "Access is an ongoing individual right under the Privacy Rule framework taught in training.",
  },
  {
    id: "draft-v1-014",
    parentConceptId: "t-41",
    variantMove: "boundary",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "security",
    tags: ["security-rule-scope", "draft-expansion"],
    difficulty: 1,
    type: "mcq",
    prompt:
      "Which statement best matches the Security Rule’s role?",
    options: [
      { key: "a", text: "It is mainly the list of permitted treatment disclosures" },
      { key: "b", text: "It requires covered entities to establish safeguards for ePHI" },
      { key: "c", text: "It replaces the need for any Privacy Rule policies" },
      { key: "d", text: "It only applies to paper medical records in locked cabinets" },
    ],
    correctKey: "b",
    explanation: "Security Rule = ePHI safeguards; permitted uses are Privacy Rule.",
  },
  {
    id: "draft-v1-015",
    parentConceptId: "t-42",
    variantMove: "setting",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "security",
    tags: ["security-rule-scope", "ephi", "draft-expansion"],
    difficulty: 1,
    type: "tf",
    prompt:
      "True or False: A paper chart left on a printer tray is a Privacy Rule / physical handling concern, but the Security Rule’s technical safeguards focus on electronic PHI (ePHI), not paper alone.",
    options: [
      { key: "a", text: "True" },
      { key: "b", text: "False" },
    ],
    correctKey: "a",
    explanation: "Parent: Security Rule applies to ePHI; paper issues are still serious under Privacy/physical safeguards framing.",
  },
  {
    id: "draft-v1-016",
    parentConceptId: "t-47",
    variantMove: "failure",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "safeguards",
    tags: ["safeguard-types", "draft-expansion"],
    difficulty: 1,
    type: "mcq",
    prompt:
      "Requiring unique user IDs and automatic logoff for the EHR is best categorized as which safeguard type?",
    options: [
      { key: "a", text: "Technical" },
      { key: "b", text: "Only “procedural marketing”" },
      { key: "c", text: "A Privacy Rule authorization form" },
      { key: "d", text: "Breach media notice" },
    ],
    correctKey: "a",
    explanation: "Access control / logoff patterns are technical safeguards in the Security Rule structure.",
  },
  {
    id: "draft-v1-017",
    parentConceptId: "t-47",
    variantMove: "setting",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "safeguards",
    tags: ["safeguard-types", "physical", "draft-expansion"],
    difficulty: 1,
    type: "mcq",
    prompt:
      "Locking the telehealth closet where spare workstations are stored overnight is primarily an example of a ________ safeguard.",
    options: [
      { key: "a", text: "Physical" },
      { key: "b", text: "Transaction code set" },
      { key: "c", text: "Criminal prosecution tool" },
      { key: "d", text: "Marketing authorization" },
    ],
    correctKey: "a",
    explanation: "Facility/workstation control is physical safeguards territory.",
  },
  {
    id: "draft-v1-018",
    parentConceptId: "t-48",
    variantMove: "boundary",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "safeguards",
    tags: ["implementation-specs", "draft-expansion"],
    difficulty: 1,
    type: "tf",
    prompt:
      "True or False: In Security Rule structure used in your training, standards are requirements CEs must comply with, and implementation specifications are the tasks/methods that must be considered or implemented as specified (required vs addressable).",
    options: [
      { key: "a", text: "True" },
      { key: "b", text: "False" },
    ],
    correctKey: "a",
    explanation: "Matches parent item on standards vs implementation specifications.",
  },
  {
    id: "draft-v1-019",
    parentConceptId: "t-54",
    variantMove: "failure",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "breach",
    tags: ["breach-def", "draft-expansion"],
    difficulty: 1,
    type: "scenario",
    prompt:
      "An MA accidentally emails a spreadsheet of patient names and diagnoses to the wrong external address. Under the composite definition used in your training, this incident is best described as:",
    options: [
      { key: "a", text: "Only a “customer service issue,” never a potential breach" },
      { key: "b", text: "A potential breach involving unauthorized disclosure of PHI that compromises privacy/security" },
      { key: "c", text: "Impossible to be a breach because email is encrypted in transit sometimes" },
      { key: "d", text: "Only a Security Rule issue if the file was printed first" },
    ],
    correctKey: "b",
    explanation: "Unauthorized disclosure of PHI/ePHI compromising privacy/security matches the composite breach framing.",
  },
  {
    id: "draft-v1-020",
    parentConceptId: "t-55",
    variantMove: "boundary",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "breach",
    tags: ["breach-notification", "draft-expansion"],
    difficulty: 2,
    type: "tf",
    prompt:
      "True or False: Breach notification is required in every circumstance of unauthorized access, with no risk assessment or exceptions considered under the Breach Notification Rule framework taught in your materials.",
    options: [
      { key: "a", text: "True" },
      { key: "b", text: "False" },
    ],
    correctKey: "b",
    explanation: "Parent item: notification is not automatic regardless of circumstances — assessment/exceptions matter.",
  },
  {
    id: "draft-v1-021",
    parentConceptId: "t-55",
    variantMove: "temporal",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "breach",
    tags: ["breach-notification", "draft-expansion"],
    difficulty: 2,
    type: "mcq",
    prompt:
      "After a confirmed breach requiring individual notice, the MA’s best immediate operational move is:",
    options: [
      { key: "a", text: "Ignore it if fewer than 50 patients might be affected" },
      { key: "b", text: "Follow the organization’s breach response process and escalate to the designated privacy/security lead promptly" },
      { key: "c", text: "Post patient names on social media to “warn the community”" },
      { key: "d", text: "Delete the audit logs so OCR cannot see them" },
    ],
    correctKey: "b",
    explanation: "Operational emphasis: escalate into the formal breach process; MAs do not freelance notification strategy.",
  },
  {
    id: "draft-v1-022",
    parentConceptId: "t-61",
    variantMove: "actor",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "enforcement",
    tags: ["ocr-role", "draft-expansion"],
    difficulty: 2,
    type: "mcq",
    prompt:
      "Which activity is generally NOT an OCR civil-enforcement tool listed in your training (the “does not apply” pattern)?",
    options: [
      { key: "a", text: "Investigating complaints" },
      { key: "b", text: "Conducting compliance reviews/audits" },
      { key: "c", text: "Criminal prosecution (typically DOJ territory)" },
      { key: "d", text: "Receiving and reviewing HIPAA complaints" },
    ],
    correctKey: "c",
    explanation: "OCR civil tools vs criminal prosecution through DOJ — same distinction as parent item.",
  },
  {
    id: "draft-v1-023",
    parentConceptId: "t-62",
    variantMove: "boundary",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "enforcement",
    tags: ["ocr-role", "draft-expansion"],
    difficulty: 2,
    type: "tf",
    prompt:
      "True or False: OCR may review complaints it receives but does not necessarily take formal action on every complaint.",
    options: [
      { key: "a", text: "True" },
      { key: "b", text: "False" },
    ],
    correctKey: "a",
    explanation: "Matches parent: OCR reviews complaints but may only act on certain ones.",
  },
  {
    id: "draft-v1-024",
    parentConceptId: "t-71",
    variantMove: "setting",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "admin-simp",
    tags: ["transactions", "draft-expansion"],
    difficulty: 1,
    type: "scenario",
    prompt:
      "A covered provider submits electronic claim transactions to a payer. Under Administrative Simplification training, the provider must:",
    options: [
      { key: "a", text: "Use any homemade CSV format they invent each week" },
      { key: "b", text: "Use an adopted transaction standard appropriate for that transaction/practice type" },
      { key: "c", text: "Avoid all electronic claims forever" },
      { key: "d", text: "Only use paper CMS-1500 even when required to use standard electronic transactions" },
    ],
    correctKey: "b",
    explanation: "Parent: CEs conducting standard transactions must use adopted standards.",
  },
  {
    id: "draft-v1-025",
    parentConceptId: "t-72",
    variantMove: "boundary",
    reviewStatus: "draft",
    sourceRef: "DRAFT expansion v1 — pending review",
    moduleId: "admin-simp",
    tags: ["code-sets", "draft-expansion"],
    difficulty: 1,
    type: "tf",
    prompt:
      "True or False: HIPAA Administrative Simplification requires specific code sets to be used for transactions based on the type of practice/transaction context taught in your materials.",
    options: [
      { key: "a", text: "True" },
      { key: "b", text: "False" },
    ],
    correctKey: "a",
    explanation: "Matches parent code-set obligation item.",
  },
];

export const HIPAA_EXPANSION_DRAFT_REVIEWERS = [
  "Sneha — compliance / answer-key accuracy",
  "Sonu — MA-facing clarity and scenario realism",
] as const;
